---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:

  - name:  Update all packages
    become: true
    yum:
      name: '*'
      update_cache: yes
      state: latest

  - name: Install Nginx
    command: amazon-linux-extras install nginx1.12=latest -y
    args:
      creates: /sbin/nginx

  - name: Enable NGINX and ensure it's enabled
    systemd:
      name: nginx
      state: started
      enabled: yes






    
